# Uncomment this line to define a global platform for your project
platform :ios, "6.0"

target "FastTextSearch" do

pod 'TAStringDataStructures', :git => 'https://github.com/tdansel88/TAStringDataStructures.git'

end

